const data = [
    {
      key: 1,
      title: 'Finish the task1',
      category: 'Zıpzıp',
      endDate: 'Aug 14 2024',
      status: 'In Preview',
      priority: 'High',
      progress: 90,
      description: 'Lorem ipsum sit amet.',
    },
    {
      key: 2,
      title: 'Finish the task2',
      category: 'Spark',
      endDate: 'Aug 27 2024',
      status: 'Not Started',
      priority: 'High',
      progress: 0,
      description: 'Lorem ipsum sit amet.',
    },
    {
      key: 3,
      title: 'Make the window pop',
      category: 'WebPanel',
      endDate: 'Sep 7 2024',
      status: 'In Progress',
      priority: 'Normal',
      progress: 40,
      description: <div>deneme</div>,
    },
    {
      key: 4,
      title: 'Get the job done',
      category: 'Spark',
      endDate: 'Aug 4 2024',
      status: 'Completed',
      priority: 'Low',
      progress: 80,
      description: 'Lorem ipsum sit amet.',
    },
  ];